# Generated by Django 5.1.4 on 2025-01-26 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0002_educationalresource'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EducationalResource',
        ),
    ]
